/**
 * Type overrides for Google Apps Script
 * Auto-generated by gas-type-checker
 */

declare namespace GoogleAppsScript {
  namespace Card_Service {
    // Fix for Gmail draft response type
    interface UpdateDraftActionResponse {
      printJson(): string;
    }
  }
}

// Global type aliases for common mistakes
type GmailDraftActionResponse = GoogleAppsScript.Card_Service.UpdateDraftActionResponse;
